platform :ios, '8.0'

source 'https://bitbucket.org/prolificinteractive/pibrary-ios'
source 'https://github.com/CocoaPods/Specs.git'

#Per pod basis warning inhibits? =>  use :inhibit_warnings => true
inhibit_all_warnings!

use_frameworks!

target 'Bellerophon' do
	pod 'Alamofire'
	pod 'AlamofireObjectMapper'
	pod 'Bellerophon', :path => "../"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end